# sep e end
print('chamada otiginal')
print(1, 2, 3)
print('alterando o sep')
print(1, 2, 3, sep="...")
print()
print('alterando o end')
print('prints separados', end=" ")
print('mas impressos', end=" ")
print('em uma mesma linha')
